### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Moonlgiht111** [WhishN/altV--NPCVehicleSync#2]
When will they release a new update?

**Comment by WhishN** [comment]
Thx for bumping. I'm working on it. Release Version will come this week.

**Comment by WhishN** [comment]
Due to private issues, and my gta not working i cant test atm. I will test and update as soon as i get ot to work again.

**Comment by Moonlgiht111** [comment]
Okay! Thanks a lot

**Comment by FDiskas** [comment]
+1 Subscribed also

**Comment by WhishN** [comment]
As i Finally Fixed My GTA. I Updated the Code to be able to run under Dev/RC now

**Comment by FDiskas** [comment]
did you pushed the changes?
